on: [push, pull_request]

name: CI

jobs:
  build:
    name: hreq
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime:
          - tokio
          # - async-std
        server:
          - ""
          - "server"
        feature:
          - ""
          - gzip
          - tls
        what:
          - "--doc"
          - "--tests"
        exclude:
          - server: ""
            what: "--tests"
    env:
      RUST_BACKTRACE: "1"
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: ${{ matrix.what }} --no-default-features --features "${{ matrix.runtime }} ${{ matrix.server }} ${{ matrix.feature }}"
